# Generated by Django 4.0.1 on 2022-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registry', models.CharField(max_length=100)),
            ],
        ),
    ]
