# Generated by Django 4.0.1 on 2022-01-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_pending_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_request',
            name='Verification_Code',
            field=models.CharField(default='unverified', max_length=100),
        ),
    ]
