# Generated by Django 4.0.1 on 2022-01-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_pending_request_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='closed', max_length=100)),
            ],
        ),
    ]
