# Generated by Django 3.2.3 on 2022-02-02 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0013_auto_20220128_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_request',
            name='Driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_app.driver'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='LastAllowed',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 31, 6, 605550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='drives_car',
            name='Pub_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 31, 6, 594415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pending_request',
            name='Last_Captured',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 31, 6, 595368, tzinfo=utc)),
        ),
    ]
